{
    "application": False,
    "author": "Marc Wimmer (marc@itewimmer.de)",
    "auto_install": True,
    "conflicts": [],
    "css": [],
    "data": ["views/field_form.xml", "views/model_form.xml"],
    "demo_xml": [],
    "depends": ["base"],
    "installable": True,
    "external_dependencies": {"python": ["arrow"]},
    "js": [],
    "name": "cleardb",
    "qweb": [],
    "test": [],
    "version": "13.0.1.0",
    "demo": [],
}
